### PR TITLE
Upgrade bitcoin requirement from 0.28.1 to 0.29.1

### PR DESCRIPTION
**Pull request by danielgranhao**
Upgrade `bitcoin` dependency to 0.29.1 to solve compatibility issues with LDK 0.0.111

### CODE REVIEW

**Review by rajarshimaitra — APPROVED** [review]
Sorry fat finger over the close button.. 

tACK b047922bcbdf2796365dc400e661e6ea34477085

We also need this to use this lib in bdk_core..

**Review by notmandatory — APPROVED** [review]
ACK b047922bcbdf2796365dc400e661e6ea34477085

**Comment by notmandatory** [comment]
@danielgranhao Thanks for the update. It looks like it's ready to merge but can you [sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) first?

**Comment by danielgranhao** [comment]
@notmandatory Sorry about that, done!

**Comment by benthecarman** [comment]
Looks like there is a compile error

**Comment by afilini** [comment]
Yes, I think `BlockHash` isn't `Default` anymore. You can try replacing that line with `BlockHash::all_zeros()`, it should work the same.

**Comment by danielgranhao** [comment]
Hum.. I'm not sure why this is failing. The unsigned commit seemed fine and I can't even find the line that is erroring in the repo 🤔

**Comment by afilini** [comment]
The line is here:

https://github.com/bitcoindevkit/rust-esplora-client/blob/8c93e0dd7cd7783c304663dff21369ea3c0a2edd/src/lib.rs#L494

**Comment by danielgranhao** [comment]
Thanks! Forgot to rebase 🤦  should be fixed now

**Comment by afilini** [comment]
You need to run `cargo fmt` to format the code

**Pull request merged**
