### PR TITLE
Replace `ureq` with `minreq` for `blocking`

### PR DESCRIPTION
**Pull request by tnull**
Taking this over from #57.

So far just a few minor adjustments on top of #57. Tested that syncing LDK works with the updated blocking client (in addition to the tests here).

### CODE REVIEW

**Comment by notmandatory** [comment]
You may need to pin some dependencies to get CI to build, see https://github.com/bitcoindevkit/bdk/blob/f099b42005b5310cee51fa2eaa29f94d76753bd7/.github/workflows/cont_integration.yml#L30C7-L36C49

**Comment by notmandatory** [comment]
I'm much less concerned about pinning dev only dependencies so I don't see a reason to redo the CI to make progress on this PR. For BDK there's a PR to change the CI to use NIX which would also remove the auto-downloaded bitcoind / electrsd issue that required these broken for msrv dev dependencies (https://github.com/bitcoindevkit/bdk/pull/1257). Once we get that PR into BDK we should be able to do something similar for this project with @storopoli 's help.

**Comment by storopoli** [comment]
Yeah count me in. Propagating Nix CI PRs throughout BDK's ecosystem should be a breeze after https://github.com/bitcoindevkit/bdk/pull/1257

**Comment by notmandatory** [comment]
Rather than mixing the discussion and fixes for the MSRV issue into this PR I've create a stand-alone PR #76 for it.

**Comment by notmandatory** [comment]
I merged #79 so this PR should be re-based again.

**Comment by notmandatory** [comment]
I had to push another commit to fix the CI. Apparently the latest version of `jobserver` has an MSRV of 1.63 so we do not need to pin it anymore (and our old pinned version 1.26 does not work).

**Review by notmandatory — APPROVED** [review]
ACK 6a598b270cd64bdadde69126db1a2b200ce96231

**Pull request merged**
