### PR TITLE
chore: bump version to 0.11.0

### PR DESCRIPTION
**Pull request by notmandatory**

### CODE REVIEW

**Review by oleonardolima — APPROVED** [review]
ACK e2bd28b86f8cf0585f8eb0fb9d5f65024abbc369

**Comment by LagginTimes** [comment]
ACK e2bd28b86f8cf0585f8eb0fb9d5f65024abbc369

**Comment by notmandatory** [comment]
The `security-framework-sys` bumped their MSRV to 1.65 18 days ago so for MSRV we need to pin it back to 2.11.1. I'm not sure why CI didn't catch this when I made this PR 4 days ago. The CI build steps fail when I run them locally for 1.63.

**Review by ValuedMammal — APPROVED** [review]
ACK 23485a95e07c1ba8044634117366f6f7ca29fdf8

**Comment by LagginTimes** [comment]
ACK 23485a95e07c1ba8044634117366f6f7ca29fdf8

**Pull request merged**
