### PR TITLE
chore(deps): upgrade `rust-bitcoin` to `0.32.0`

### PR DESCRIPTION
**Pull request by oleonardolima**
`partially fixes` [#1422](https://github.com/bitcoindevkit/bdk/issues/1422)

### Description

It updates the rust-bitcoin to 0.32.0, the `bitcoin`crate dependency and `electrsd` to `0.28.0`.

_NOTE: The overall BDK update to `0.32.0` still requires and depends on some other crates, please refer to [#1422](https://github.com/bitcoindevkit/bdk/issues/1422)._

### Notes to the reviewers

It's open for any comments.

### Changelog notice

- Update the `bitcoin` crate dependency to `0.32.0`
- Update the `electrsd` crate dependency to `0.28.0`

#### All Submissions:

* [x] I've signed all my commits
* [x] I followed the [contribution guidelines](https://github.com/bitcoindevkit/bdk/blob/master/CONTRIBUTING.md)
* [x] I ran `cargo fmt` and `cargo clippy` before committing

#### New Features:

* [ ] I've added tests for the new feature
* [ ] I've added docs for the new feature

#### Bugfixes:

* [ ] This pull request breaks the existing API
* [ ] I've added tests to reproduce the issue which are now passing
* [ ] I'm linking the issue being fixed by this PR

### CODE REVIEW

**Comment by tcharding** [comment]
FWIW the PR description is stale, all the upgrades upto and including `miniscript` are done now (including `bitcoind`).

**Comment by notmandatory** [comment]
Thanks! LGTM, just need to remove the patches and it should be ready to go.

**Comment by notmandatory** [comment]
I just published `electrum-client` 0.20.0: https://crates.io/crates/electrum-client/0.20.0

**Comment by notmandatory** [comment]
The `electrsd` 0.28.0 crate with `rust-electrum-client` 0.20 is published so should be able to wrap up this PR. https://crates.io/crates/electrsd/0.28.0

**Comment by oleonardolima** [comment]
> The `electrsd` 0.28.0 crate with `rust-electrum-client` 0.20 is published so should be able to wrap up this PR. https://crates.io/crates/electrsd/0.28.0

Great! I removed the patch, reword the commit and the description, should be ready to go now.

**Review by notmandatory — APPROVED** [review]
ACK 6836628f8d0da3b39256d15f6dc7d113d6bdb49e

**Pull request merged**
