### PR TITLE
feat: add way to make raw req and get url for `BlockingClient`

### PR DESCRIPTION
**Pull request by evanlinjin**
Also add method for getting from `/tx/:txid` endpoint.

### CODE REVIEW

**Review by notmandatory — APPROVED** [review]
ACK f3c0055de1c1271b98f9332bdd9cc7c00d781ac0

**Review by evanlinjin — COMMENTED** [review]
self-ACK 3b778c57625ab8f4fb9b72b4e2013af74045a846

**Review by oleonardolima — COMMENTED** [review]
post-merge ACK 3b778c57625ab8f4fb9b72b4e2013af74045a846
It just seems that it requires some dependency pinning for the MSRV

**Comment by notmandatory** [comment]
Oh ya CI is broken, same issue as on the BDK branch. I'll make a new PR to fix it.

**Comment by oleonardolima** [comment]
> Oh ya CI is broken, same issue as on the BDK branch. I'll make a new PR to fix it.

Thanks! I didn't notice that it was the same problem as https://github.com/bitcoindevkit/bdk/pull/1470

**Pull request merged**
