### PR TITLE
Add `get_merkle_block` API call

### PR DESCRIPTION
**Pull request by tnull**
We already have the `get_merkle_proof` call, but this one returns a `bitcoin::MerkleBlock`, which has additional data and is more often than not more useful than Electrum's counterpart.

### CODE REVIEW

**Comment by tnull** [comment]
Huh, I think the clippy error is unrelated to my change?

**Comment by notmandatory** [comment]
> Huh, I think the clippy error is unrelated to my change and the warning seems to only be added by the just-released 1.65.0 (see https://rust-lang.github.io/rust-clippy/master/index.html#result_large_err). Not sure how to go about it? Should I fix it here, or do we want to do that in another PR?

I think this is OK to fix in a different PR, for now you can allow the warning where needed with:
```rust
#[allow(clippy::result_large_err)]
```

**Comment by tnull** [comment]
> I think this is OK to fix in a different PR, for now you can allow the warning where needed with:

Alright, I now set the attribute crate-wide and squashed again.

**Review by notmandatory — APPROVED** [review]
utACK e40583af13bd4ce812e91476ffa489553b4a26de

**Review by vladimirfomene — APPROVED** [review]
Tested ACK

**Pull request merged**
