### PR TITLE
Run tests in a single thread, plus minor ci cleanups

### PR DESCRIPTION
**Pull request by notmandatory**
I changed the CI tests to run in a single thread (one at a time) which should improve test reliability. I also added names to all the test tasks, and remove redundant clippy checks.

### CODE REVIEW

**Comment by tnull** [comment]
Ah, if it should be single-threaded going forward, I believe the setup logic could be simplified a bit too, e.g., the premine probably doesn't need to happen synchronized via `tokio::sync::OnceCell` (but can, of course):

https://github.com/bitcoindevkit/rust-esplora-client/blob/3030d2b099330ea6f0752ba89acc294a48ac3946/src/lib.rs#L247

**Comment by notmandatory** [comment]
I think we still need that setup logic since the single thread is just the CI system running tests one at a time.. within each tests (the async ones at least) there could be multiple threads.

**Review by vladimirfomene — APPROVED** [review]
LGTM

**Comment by oleonardolima** [comment]
I wonder what's wrong with these coverage reports by coveralls being sent now 🤔.

**Pull request merged**
