### PR TITLE
Add new API call get_block_status

### PR DESCRIPTION
**Pull request by gcomte**

### CODE REVIEW

**Comment by vladimirfomene** [comment]
can you fix the code coverage error?

**Comment by gcomte** [comment]
> @gcomte can you fix the code coverage error?

Oh I'm sorry. Issue is fixed now.

**Review by vladimirfomene — APPROVED** [review]
Tested ACK

**Review by notmandatory — APPROVED** [review]
ACK 5fbabb8532bff339a3ec19c5e4c3157439637696

**Pull request merged**
