### PR TITLE
chore: bump version to 0.9.0

### PR DESCRIPTION
**Pull request by evanlinjin**

### CODE REVIEW

**Review by oleonardolima — APPROVED** [review]
ACK 0563a902ac58677be53a9d0df9bb93114f670588
~~It just seems that it requires some dependency pinning for the MSRV~~ https://github.com/bitcoindevkit/rust-esplora-client/pull/89

**Review by notmandatory — APPROVED** [review]
ACK 0563a902ac58677be53a9d0df9bb93114f670588

**Comment by notmandatory** [comment]
This needs to be rebased since #89 fixed the ci issue.

**Review by evanlinjin — COMMENTED** [review]
self-ACK 0cca85dfbf01bf3d5ed24ed5194f38eb15413610

**Review by oleonardolima — APPROVED** [review]
ACK 0cca85dfbf01bf3d5ed24ed5194f38eb15413610

**Pull request merged**
